# Irreducible Operators and other Group Representation Examples

The calculations below relate to Wu-Ki Tung (Group Theory in Physics book), p. 56-58, on irreducible vectors and operators.




In [1]:
import numpy as np
np.set_printoptions(suppress=True)

Irrep matrices from: https://arxiv.org/pdf/1112.0687.pdf
Include 3 irreps: lambda-2 (3-dim), lambda-3 (2-dim), and lambda-4 (3-dim)
call the generators a2a12, a2a23, a2a34 for (12), (23), and (34) for lambda-2, etc.



In [8]:
nmu=3
ng = 24 # S4 group has order=24
def build(g,a12,a23,a34):
    g[1] = a12
    g[2] = a23
    g[3] = a34
    g[4] = a12@a23@a12
    g[5] = a12@a23@a34@a23@a12
    g[6] = a23@a34@a23
    g[7] = a12@a34
    g[8] = a12@a23@a12@a23@a34@a23
    g[9] = a12@a23@a34@a23@a12@a23
    g[10] = a12@a23
    g[11] = a23@a12
    g[12] = a12@a23@a34@a23
    g[13] = a23@a34@a23@a12
    g[14] = a12@a23@a34@a12
    g[15] = a12@a34@a23@a12
    g[16] = a23@a34
    g[17] = a34@a23
    g[18] = a12@a23@a34
    g[19] = a34@a23@a12
    g[20] = a12@a23@a12@a23@a34@a23@a12
    g[21] = a23@a34@a12
    g[22] = a12@a23@a34@a23@a12@a23@a12
    g[23] = a12@a34@a23
    
g2 = np.zeros(ng*9).reshape(ng,3,3)
g3 = np.zeros(ng*4).reshape(ng,2,2)
g4 = np.zeros(ng*9).reshape(ng,3,3)

a2a12 = np.array([[1,0,0],[-1,-1,0],[1,0,-1]])
a2a23 = np.array([[0,1,0],[1,0,0],[0,0,-1]])
a2a34 = np.array([[-1,0,0],[0,0,1],[0,1,0]])
g2[0] = np.diag([1,1,1])
build(g2,a2a12,a2a23,a2a34)

a3a12 = np.array([[1,0],[-1,-1]])
a3a23 = np.array([[0,1],[1,0]])
a3a34 = np.array([[1,0],[-1,-1]])
g3[0] = np.diag([1,1])
build(g3,a3a12,a3a23,a3a34)

a4a12 = np.array([[-1,-1,-1],[0,1,0],[0,0,1]])
a4a23 = np.array([[0,1,0],[1,0,0],[0,0,1]])
a4a34 = np.array([[1,0,0],[0,0,1],[0,1,0]])
g4[0] = np.diag([1,1,1])
build(g4,a4a12,a4a23,a4a34)

sw = np.array([[1,0,0],
               [0,0,1],
               [0,1,0]])

In [30]:
U = np.zeros(ng*36).reshape(ng,6,6)
for i in range(ng):
    U[i,0:3,0:3] = g2[i]
    U[i,3:6,3:6] = g2[i]
    
P = np.zeros(36*9).reshape(3,3,6,6)
for i in range(3):
    for j in range(3):
        for k in range(ng):
            P[i,j] = P[i,j] + nmu/ng * np.linalg.inv(g2[k])[j,i] * U[k]

print(P[2,1])
print()
print(P[0,2])
print()

E = np.zeros(36).reshape(6,6)
for i in range(3):
    E = E + P[i,i]

print(E)
print(np.allclose(E,np.diag([1,1,1,1,1,1])))


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
True



Purpose of the rotation matrices below is to create a unitary matrix, R, that is fairly scrambled


In [65]:
th = np.pi/6
R1 = np.array([[np.cos(th),-np.sin(th)],[np.sin(th),np.cos(th)]])
R2 = np.zeros(36).reshape(6,6)
R2[0:2,0:2]=R1
R2[2:4,2:4] = R1
R2[4:6,4:6] = R1
swap15 = np.zeros(36).reshape(6,6)
swap15[5,1] = 1
swap15[1,5] = 1
swap15[0,0] = 1
swap15[2,2] = 1
swap15[3,3] = 1
swap15[4,4] = 1
R = R2 @ swap15 @ R2
RT = R.T
print(RT)

[[ 0.75       0.4330127  0.         0.        -0.25       0.4330127]
 [-0.4330127 -0.25       0.         0.        -0.4330127  0.75     ]
 [ 0.         0.         0.5        0.8660254  0.         0.       ]
 [ 0.         0.        -0.8660254  0.5        0.         0.       ]
 [-0.25       0.4330127  0.         0.         0.75       0.4330127]
 [-0.4330127  0.75       0.         0.        -0.4330127 -0.25     ]]


In [68]:
U2 = np.zeros(ng*36).reshape(ng,6,6)
for i in range(ng):
    U2[i] = RT @ U[i] @ R
        
P = np.zeros(36*9).reshape(3,3,6,6)
for i in range(3):
    for j in range(3):
        for k in range(ng):
            P[i,j] = P[i,j] + nmu/ng * np.linalg.inv(g2[k])[j,i] * U2[k]

print(P[2,1])
print()
print(P[0,2])
print()

E = np.zeros(36).reshape(6,6)
for i in range(3):
    E = E + P[i,i]

print('Check if projection operator is complete:')
print(np.allclose(E,np.diag([1,1,1,1,1,1])))

[[-0.10825318 -0.1875      0.         -0.          0.32475953 -0.1875    ]
 [-0.1875     -0.32475953  0.          0.          0.5625     -0.32475953]
 [ 0.21650635 -0.125       0.          0.          0.21650635  0.375     ]
 [-0.375       0.21650635  0.          0.         -0.375      -0.64951905]
 [-0.10825318 -0.1875     -0.          0.          0.32475953 -0.1875    ]
 [ 0.0625      0.10825318  0.          0.         -0.1875      0.10825318]]

[[ 0.         -0.          0.375      -0.64951905  0.          0.        ]
 [ 0.          0.         -0.21650635  0.375      -0.         -0.        ]
 [ 0.375       0.64951905  0.          0.          0.375      -0.21650635]
 [ 0.21650635  0.375       0.          0.          0.21650635 -0.125     ]
 [ 0.         -0.         -0.125       0.21650635  0.         -0.        ]
 [-0.          0.         -0.21650635  0.375      -0.         -0.        ]]

Check if projection operator is complete:
True



# Projection Operator Example

The calculation below shows that the projection operator's indices refer to the label of the basis vector in the invariant subspace.  In this case, the representation U2 is the direct sum of two copies of the 3x3 irrep for S4, in a scrambled basis so that the representation matrices in U2 are not too simple looking.

e0 through e5 are the irreducible basis vectors.  e0, e1, e2 are the basis vectors for the first invariant subspace, and e3, e4, e5 are for the second invariant subspace.  So you can see that the test vector ee, which is set to be e4, corresponds to the label 1, as far as the projection operator is concerned.  So when the projection operator transforms e4, it expect to see a "label 1" basis vector as input, and its output is a "label 0" basis vector. So in this case, its output in e3, which is a "label 0" basis vector in the second invariant subspace.


In [92]:
ee = RT@np.array([0,0,0,0,1,0])
e0 = RT@np.array([1,0,0,0,0,0])
e1 = RT@np.array([0,1,0,0,0,0])
e2 = RT@np.array([0,0,1,0,0,0])
e3 = RT@np.array([0,0,0,1,0,0])
e4 = RT@np.array([0,0,0,0,1,0])
e5 = RT@np.array([0,0,0,0,0,1])

print(e0)
print(e1)
print(e2)
print(e3)
print(e4)
print(e5)
print()
print(P[0,1]@ee)
print(np.allclose(P[0,1]@ee,e3))


[ 0.75      -0.4330127  0.         0.        -0.25      -0.4330127]
[ 0.4330127 -0.25       0.         0.         0.4330127  0.75     ]
[ 0.         0.         0.5       -0.8660254  0.         0.       ]
[0.        0.        0.8660254 0.5       0.        0.       ]
[-0.25      -0.4330127  0.         0.         0.75      -0.4330127]
[ 0.4330127  0.75       0.         0.         0.4330127 -0.25     ]

[ 0.         0.         0.8660254  0.5        0.        -0.       ]
True


In [4]:
def orth(a,b, i,j,k,l):
    global ng
    s = 0
    for ii in range(ng):
        s += np.linalg.inv(a[ii])[k,i] * b[ii,j,l]
    return(s)

print(orth(g4,g4,1,1,1,1))


8.0


In [170]:
# test Thm 3.5, p. 41 of Wu-Ki Tung
# let D_mu = g2, D_nu = g2a
def ttt(d1, d2):
    n1 = len(d1[0])
    n2 = len(d2[0])
#     X = np.random.randint(low=4, size=(n1,n2)) # X could be any n1xn2 matrix
    X = np.array([[0,0,0],[0,0,1],[0,0,0]])
    M = np.zeros(n1*n2).reshape(n1,n2)
    for i in range(len(d1)):
        M = M + np.linalg.inv(d1[i]) @ X @ d2[i]
    N = np.linalg.inv(d1[6]) @ M @ d2[6]
    print(X)
    print(M)
    print(N)
    print(np.allclose(M,N))

ttt(g2a,g2)

m=2,n=1
k=1, l=2


[[0 0 0]
 [0 0 1]
 [0 0 0]]
[[8. 0. 0.]
 [0. 0. 8.]
 [0. 8. 0.]]
[[8. 0. 0.]
 [0. 0. 8.]
 [0. 8. 0.]]
True


In [4]:
I = np.diag([1,1])
print(I)
Z = I-I
print(Z)

[[1 0]
 [0 1]]
[[0 0]
 [0 0]]


In [5]:
g = np.array([I, a@b, a@a@b, a@a@a@b, a, a@a])
print(g)

[[[ 1  0]
  [ 0  1]]

 [[ 0 -1]
  [-1  0]]

 [[ 1  0]
  [ 1 -1]]

 [[-1  1]
  [ 0  1]]

 [[ 0 -1]
  [ 1 -1]]

 [[-1  1]
  [-1  0]]]


In [6]:
# find index of x, in the array g
def dex(g,x):
    for i in range(len(g)):
        y=abs(np.around(g[i]-x,decimals=3))
        if np.sum(y)<0.001:
            return i
    return -1

In [7]:
dex(g,g[4]@g[3])

1

In [61]:
n=len(g)
mult = np.zeros((n,n), dtype=np.int_)
for i in range(n):
    for j in range(n):
        x = g[i]@g[j]
        m = dex(g,x)
        mult[i,j] = m
print(mult)

[[0 1 2 3 4 5]
 [1 0 5 4 3 2]
 [2 4 0 5 1 3]
 [3 5 4 0 2 1]
 [4 2 3 1 5 0]
 [5 3 1 2 0 4]]


In [10]:
def inv(i):
    for j in range(len(mult)):
        if mult[i,j]==0:
            return j

In [11]:
myclass = []
def addnewclass(x):
    for i in myclass:
        if x in i:
            return
    myclass.append(set([x]))

def addclass(x,y):
    # assume x and/or y are present
    for i in myclass:
        if x in i:
            i.add(y)
            return
        if y in i:
            i.add(x)
            return
        

In [12]:
n=len(mult)
for i in range(n):
    addnewclass(i)
    for j in range(n):
        if i==j:
            continue
        x = mult[inv(j),mult[i,j]]
        # i and x are in same class
        addclass(i,x)

In [13]:
print(myclass)

[{0}, {1, 2, 3}, {4, 5}]


--------------

regrep = regular representation

--------------

In [85]:
n=len(g)
aa = np.array([np.zeros((n,n))])
regrep = aa
for i in range(n-1):
    regrep=np.append(regrep, aa, 0)
print(regrep) 
regrep.shape

[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


(6, 6, 6)

In [86]:
n=len(regrep)
for i in range(n):
    for j in range(n):
        for k in range(n):
            ii = mult[i,k]
            if(j==ii):
                regrep[i,j,k]=1
            else:
                regrep[i,j,k]=0
print(regrep)

[[[1. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 1.]]

 [[0. 1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]]

 [[0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1. 0.]
  [1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0.]]]


In [87]:
n=len(g)
mult2 = np.zeros((n,n), dtype=np.int_)
for i in range(n):
    for j in range(n):
        x = regrep[i]@regrep[j]
        m = -555
        for ii in range(n):
            if(np.allclose(x, regrep[ii])):
                m = ii
        mult2[i,j] = m
print(mult2)

[[0 1 2 3 4 5]
 [1 0 5 4 3 2]
 [2 4 0 5 1 3]
 [3 5 4 0 2 1]
 [4 2 3 1 5 0]
 [5 3 1 2 0 4]]


In [88]:
np.allclose(mult, mult2)

True

In [136]:
x = np.array([1,1,1,0,0,0])
bb=regrep@x
print(bb)
for i in range(len(bb)):
    for j in range(0,i):
        bb[i] = bb[i] - (bb[i]@bb[j])*bb[j]
    if not np.allclose(bb[i],np.zeros(n)):
        bb[i] = bb[i]/np.linalg.norm(bb[i])

print(bb)

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0. 1.]]
[[ 0.57735027  0.57735027  0.57735027  0.          0.          0.        ]
 [ 0.25819889  0.25819889 -0.51639778  0.          0.          0.77459667]
 [ 0.31622777 -0.47434165  0.15811388  0.          0.79056942  0.15811388]
 [-0.40824829  0.20412415  0.20412415  0.81649658  0.20412415  0.20412415]
 [-0.         -0.         -0.         -0.         -0.          0.        ]
 [-0.         -0.         -0.         -0.         -0.          0.        ]]


In [143]:
b = np.array([[0,0,0,1,0,0],
            [0,0,0,0,1,0],
            [0,0,0,0,0,1],
             [1,0,0,0,0,0],
             [0,1,0,0,0,0],
             [0,0,1,0,0,0]])
a = b.T
print(a)
print(b)

[[0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]
[[0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]]


In [145]:
np.allclose(a@b, np.diag([1,1,1,1,1,1]))

True

In [147]:
U = np.array(
    [[1,2,3,0,0,0],
    [4,5,6,0,0,0],
    [7,8,9,0,0,0],
    [0,0,0,1,0,0],
    [0,0,0,0,1,0],
    [0,0,0,0,0,1]])
print(U)

[[1 2 3 0 0 0]
 [4 5 6 0 0 0]
 [7 8 9 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [148]:
b@U@a

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 2, 3],
       [0, 0, 0, 4, 5, 6],
       [0, 0, 0, 7, 8, 9]])

In [151]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
yy = np.diag([2,5,7])
print(yy@x)
print(x@yy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [20 25 30]
 [49 56 63]]
[[ 2 10 21]
 [ 8 25 42]
 [14 40 63]]
